apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/vinay/eks-dm:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/vinay/eks-dm:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: eks-dm
        chartPath: charts/eks-dm
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/vinay/eks-dm'
          image.tag: '{{.DIGEST_HEX}}'
